site_name: Windows CI/CD Systems

nav:
  - Home: index.md
  - Environment:
    - Package Manager: environment\package_manager.md
  - Stages:
    - Overview: stages\index.md
    - Code Base Docs: stages\code_base_docs.md
  - Jenkins:
    - Overview: jenkins\index.md

theme: cinder

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
