site_name: Windows CI/CD Systems
theme: cinder

nav:
  - Home: index.md
  - Environment:
    - Package Manager: environment/package_manager.md
  - Stages:
    - Overview: stages/index.md
    - Code Base Docs: stages/code_base_docs.md
  - Jenkins: jenkins/index.md

social:
  - type: 'github'
  - link: 'https://github.com/SashaNullptr'

repo_name: GitHub
repo_url: https://github.com/SashaNullptr/WindowsCICD
